name:                          releases

on:
  push:
    tags:
      - '*'

jobs:
  notifications:
    runs-on:                   ubuntu-latest
    steps:
    - uses:                    actions/checkout@master
    - name:                    Fetch commits
      run:                     |
        git fetch --prune --unshallow --tags
    - name:                    Create changelogs
      id:                      changelogs
      uses:                    heineiuo/create-changelogs@master
    - name:                    Get tag
      id:                      tag
      uses:                    dawidd6/action-get-tag@v1
    - name:                    Push to Telegram
      uses:                    appleboy/telegram-action@master
      with:
        to:                    ${{ secrets.TELEGRAM_TO }}
        token:                 ${{ secrets.TELEGRAM_TOKEN }}
        format:                markdown
        args:                  |+
          Version [${{ steps.tag.outputs.tag }}](https://gitub.com/sbertix/Swiftagram) was just released. Please consider updating your code.
          ${{ steps.changelogs.outputs.changelogs }}
  documentation:
    runs-on:                   macos-latest
    steps:
    - uses:                    actions/checkout@v1
    - uses:                    steven0351/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        args:                  "--theme fullwidth --author \"Stefano Bertagno\""
